// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdN8LXltvjCMMolkgOucy0IYDr_gkD0OY',
    appId: '1:8995605723:web:6b123930eab6b9939590fe',
    messagingSenderId: '8995605723',
    projectId: 'plat-72134',
    authDomain: 'plat-72134.firebaseapp.com',
    storageBucket: 'plat-72134.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVK9pWcsmzxKMOHmJhAnVk4xfWrslAFlQ',
    appId: '1:8995605723:android:ffeb167bd8dedde99590fe',
    messagingSenderId: '8995605723',
    projectId: 'plat-72134',
    storageBucket: 'plat-72134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhhpWWb0Rxb0fLJBMc5aACGaLEibNuhSk',
    appId: '1:8995605723:ios:bfb2fd99c3e08e099590fe',
    messagingSenderId: '8995605723',
    projectId: 'plat-72134',
    storageBucket: 'plat-72134.firebasestorage.app',
    iosBundleId: 'com.example.platDec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhhpWWb0Rxb0fLJBMc5aACGaLEibNuhSk',
    appId: '1:8995605723:ios:bfb2fd99c3e08e099590fe',
    messagingSenderId: '8995605723',
    projectId: 'plat-72134',
    storageBucket: 'plat-72134.firebasestorage.app',
    iosBundleId: 'com.example.platDec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdN8LXltvjCMMolkgOucy0IYDr_gkD0OY',
    appId: '1:8995605723:web:183babad24353b859590fe',
    messagingSenderId: '8995605723',
    projectId: 'plat-72134',
    authDomain: 'plat-72134.firebaseapp.com',
    storageBucket: 'plat-72134.firebasestorage.app',
  );
}
